# Generated by Django 5.1.5 on 2025-02-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('full_name', models.TextField(verbose_name='Полное название')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, default='dish/images/default.jpg', null=True, upload_to='dish/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.dishcategory', verbose_name='Категория')),
            ],
        ),
    ]
