# Generated by Django 5.1.5 on 2025-02-06 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='Блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Текущая цена')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('indelivery', 'В доставке'), ('delivered', 'Доставлен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('manager_name', models.CharField(max_length=100, verbose_name='Менеджер')),
                ('action', models.CharField(choices=[('to_delivery', 'Отправлено в доставку'), ('done', 'Завершено')], max_length=20, verbose_name='Действие')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='orders.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=100, verbose_name='Название блюда на момент заказа')),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена блюда на момент заказа')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
